version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - ENV=env
    ports:
      - "8080:8080"  # Expose your app port

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # Expose Redis port
    volumes:
      - redis-data:/data

volumes:
  redis-data:
